### ISSUE TITLE
Refactor: 게시글 데이터 구조 변경

### ISSUE THREAD

**Issue by starcradle101** [starcradle101/hoonie-log#29]
## 🖨️ Description
본 이슈에서는 게시글의 데이터 구조를 변경하고, 수정된 구조를 기반으로 컴포넌트를 업데이트합니다.

## 📝 To-do
- [x] 게시글 데이터 구조 변경
- [x] 불필요한 게시글 관련 라이브러리 삭제
- [x] 변경된 구조 기반 게시글 컴포넌트 업데이트

## 🧑🏻‍💻 ETC
- 기타 사항은 추후 추가 예정입니다.
