### ISSUE TITLE
Design: 게시글 목록 컴포넌트 레이아웃 수정

### ISSUE THREAD

**Issue by starcradle101** [starcradle101/hoonie-log#33]
## 🖨️ Description
본 이슈에서는 게시글 목록 컴포넌트와 게시글 미리보기 컴포넌트의 레이아웃 수정을 진행합니다.

## 📝 To-do
- [x] 게시글 목록 컴포넌트 레이아웃 수정
- [x] 게시글 미리보기 컴포넌트 레이아웃 수정
- [x] 게시글 목록 스켈레톤 UI 구현

## 🧑🏻‍💻 ETC
- 기타 사항은 추후 추가 예정입니다
