### ISSUE TITLE
Feat: GitHub OAuth 구현

### ISSUE THREAD

**Issue by starcradle101** [starcradle101/hoonie-log#4]
## 🖨️ Description
Supabase에서 GitHub OAuth를 사용한 사용자 인증 구현을 위한 이슈입니다.

## 📝 To-do
- [ ] Supabase와 프로젝트 연동
- [ ] OAuth 인증 컴포넌트 구현
- [ ] 테스트 대시보드 페이지 구현
- [ ] GitHub OAuth 인증 구현

## 🧑🏻‍💻 ETC
- 기타 사항은 추후 추가 예정입니다.
