### ISSUE TITLE
Refactor: 게시글 작성 페이지 개선

### ISSUE THREAD

**Issue by starcradle101** [starcradle101/hoonie-log#48]
## 🖨️ Description
본 이슈에서는 게시글 작성 페이지 개선을 위한 작업을 다룹니다.

## 📝 To-do
- [ ] 게시글 작성 페이지 컴포넌트 분리
- [ ] 게시글 작성 페이지 메모리 누수 문제 해결
- [ ] 게시글 작성 페이지 레이아웃 개선

## 🧑🏻‍💻 ETC
- 기타 사항은 추후 추가 예정입니다.
